# Generated by Django 6.0.6 on 2026-06-11 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID потока')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Имя')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Название')),
                ('start_education_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала обучения')),
                ('end_education_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания обучения')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID дивизиона')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Короткое название')),
                ('type_of_string', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Дивизион',
                'verbose_name_plural': 'Дивизионы',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID университета')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('city_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Город')),
                ('library_id', models.IntegerField(blank=True, null=True, verbose_name='ID библиотеки')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID дисциплины')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Название')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='parser.cohort', verbose_name='Поток')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID активности')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Название')),
                ('type', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип')),
                ('type_id', models.IntegerField(blank=True, null=True, verbose_name='ID типа')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность (мин)')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='parser.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
            },
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID программы')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Короткое название')),
                ('degree', models.CharField(blank=True, max_length=256, null=True, verbose_name='Степень')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_programs', to='parser.division', verbose_name='Дивизион')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='educational_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='parser.educationalprogram', verbose_name='Образовательная программа'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID группы')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Название')),
                ('students_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество студентов')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='parser.cohort', verbose_name='Поток')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='division',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='parser.university', verbose_name='Университет'),
        ),
    ]
