# Generated by Django 6.0.6 on 2026-06-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='solution_url',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Ссылка на страницу решения'),
        ),
    ]
