# Generated by Django 6.0.6 on 2026-06-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_add_solution_url_to_studentwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturePresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(verbose_name='Путь из API')),
                ('local_path', models.CharField(max_length=1024, verbose_name='Путь на диске')),
                ('file_hash', models.CharField(max_length=64, verbose_name='SHA-256 хэш файла')),
                ('parsed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='parser.activity', verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Презентация лекции',
                'verbose_name_plural': 'Презентации лекций',
                'unique_together': {('activity', 'file_hash')},
            },
        ),
    ]
