# Generated by Django 6.0.6 on 2026-06-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_add_lecture_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturepresentation',
            name='task',
            field=models.TextField(blank=True, null=True, verbose_name='Текст задания (последний слайд)'),
        ),
    ]
