# Generated by Django 6.0.6 on 2026-07-13 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_add_superuser'),
        ('scheduler', '0002_update_status_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('parse_structure', 'Parse Structure'), ('download_works', 'Download Works'), ('extract_pptx', 'Extract PPTX Tasks'), ('set_marks', 'Set Marks'), ('scheduled_run', 'Scheduled Run')], max_length=32, verbose_name='Команда')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], db_index=True, default='running', max_length=16, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время запуска')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='Метрики')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('output_preview', models.TextField(blank=True, default='', verbose_name='Превью вывода')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.schedule', verbose_name='Расписание')),
                ('schedule_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.schedulelog', verbose_name='Лог расписания')),
            ],
            options={
                'verbose_name': 'Запуск парсера',
                'verbose_name_plural': 'Запуски парсера',
                'ordering': ('-started_at',),
            },
        ),
    ]
