# Generated by Django 6.0.6 on 2026-07-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0007_parserrun'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentwork',
            unique_together=set(),
        ),
    ]
