# Generated by Django 6.0.6 on 2026-07-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0008_alter_studentwork_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='status',
            field=models.CharField(choices=[('no_work', 'Нет работы'), ('has_work', 'Есть работа'), ('has_mark', 'Есть отметка')], default='no_work', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='studentwork',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SHA-256 хэш файла'),
        ),
        migrations.AlterField(
            model_name='studentwork',
            name='local_path',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Путь к файлу'),
        ),
    ]
