# Generated by Django 6.0.6 on 2026-07-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('interval_seconds', models.PositiveIntegerField(default=3600, help_text='Как часто запускать процесс (в секундах)', verbose_name='Интервал (сек)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успех'), ('error', 'Ошибка')], default='running', max_length=32, verbose_name='Статус')),
                ('log_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='SHA-256 лога')),
                ('log_path', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Путь к логу')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scheduler.schedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Лог расписания',
                'verbose_name_plural': 'Логи расписаний',
                'ordering': ('-started_at',),
            },
        ),
    ]
