# Generated by Django 6.0.6 on 2026-07-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelog',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В прогрессе'), ('done', 'Завершен')], default='in_progress', max_length=32, verbose_name='Статус'),
        ),
    ]
